### ISSUE TITLE
Functionality list for map portal 

### ISSUE THREAD

**Issue by ac-willeke** [NINAnor/EAguide#5]
@nicokant, @frafra it would be great if we could make a table with functionality that exists and that DOES not exist in the map portal.
So that we are transparent to the users in what the map portal can and cannot do. In addition it would be great to give an estimate on if new functionality will be implemented or if not. 

Not sure to which page to add this info! But this is the first question most people ask me when they are curious about the map portal. 

Here is an example format:

| Functionality | Available | Possible in the future |
|------------------|--------------|------------------------------|
| Download data    | Yes       |       -       |
| Zoom to extent  | Yes        | -            |
| Connect to ipt/living norway  | No       | 2026               |
| SQL-quering of vector data | No | 2025 |
| Dashboard functionality | No | Will not be implemented |

**Comment by nicokant** [comment]
https://github.com/NINAnor/nina-catalogue/pull/38

**Comment by nicokant** [comment]
https://ninanor.github.io/nina-catalogue/features.html#maps-module

**Comment by ac-willeke** [comment]
Nice! Perfect :)
